# -*- coding: utf-8 -*-
"""KnowledegeClusters.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sthf8cQbLGozSW103Iuf0j9wWxrrhKPd
"""

import pandas as pd
skills=pd.read_csv("/content/knowledgecleansed.csv")

skills.head()

target=skills["Title"]
data=skills.drop("Title",axis=1)
feature_name=data.columns
data.head()

from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=100)

kmeans.fit(data)

predicted_clusters = kmeans.predict(data)
predicted_clusters
cluster_labels=[]
j=0
for i in predicted_clusters:
    cluster_labels.append([i,target[j]])
    j+=1
cluster_labels
testdf=pd.DataFrame(cluster_labels)
testdf=testdf.rename(columns={0: 'Class', 1: 'Title'})
testdf=testdf.sort_values('Class', ascending=True)
testdf=testdf.set_index("Class")
#testdf=testdf.groupby("Class")

centers = kmeans.cluster_centers_
labels = kmeans.labels_
print(labels)

testdf.to_csv("KnowledgeCleansed_Clusters.csv")

test=data[:1]

test

kmeans.predict(test)

import pickle
filename = 'kmeans_knowledge_cluster.sav'
pickle.dump(kmeans, open(filename, 'wb'))
#kmeans.save("kmeans_knowledge_cluster.h5")

loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(test)
print("The test data belongs to Class: ", result)
df=testdf.loc[testdf.index==result[0]]

print("The jobs are:",df.values)
#[school_df["type"]=="District"]